### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ByblackSun** [Judiks/VoiceShipControl#1]
I don’t know what steps I did wrong.       I don't have this problem when I use another ship's voice control.

After turning the voice button on or off, nothing happens even when I speak.

**Comment by Judiks** [comment]
@ByblackSun Write me in discord will chek together . Or if you won't write me in discord try to enable BepInEx console and check if there is message "Broadcasting Started" when you push the button. Or any other error :/

Version just released so can be evrything

https://discord.com/users/_judik_

**Comment by Judiks** [comment]
@ByblackSun I think I get the point. Are you trying to change the "Is voice activation button needed?" setting withot button setup and it doesn't work. Well, I see this error, but I'm thinking of removing this option in the future and leaving only push-button activation. It's best not to overload the recognizer with everything you talk about.

**Comment by chilianer** [comment]
"BepInEx console output is as follows: 
[Info: Console] Broadcasting started
[Info: Unity Log] Error: recognition request failed
[Info: Console] Error: recognition request failed"

**Comment by Judiks** [comment]
@ByblackSun you installing it with r2modman?

**Comment by Judiks** [comment]
Don't see any problems with app what can be checked from @ByblackSun request. Closing this issue
