### ISSUE TITLE
Error: recognition request failed

### ISSUE THREAD

**Issue by Judiks** [Judiks/VoiceShipControl#2]
"BepInEx console output is as follows: 
[Info: Console] Broadcasting started
[Info: Unity Log] Error: recognition request failed
[Info: Console] Error: recognition request failed"

_Originally posted by @chilianer in https://github.com/Judiks/VoiceShipControl/issues/1#issuecomment-1932150445_

**Comment by Judiks** [comment]
@chilianer i have few question.
1) You sending commands with button or voise activation?
2) You see that error message each time or sometimes text recognized as well?

Bathicaly this mod working with WEB Speech API and sending request to it with listened audio, so if you have some network issues or speaking to long it can return this error. Can be a lot cases for your problem. I need more info to envestigate it.

Try to check rocognizer with [this](https://mdn.github.io/dom-examples/web-speech-api/speech-color-changer/) page.

**Comment by chilianer** [comment]
1.I use a key.
2.Each time I try to use it, I see the same error message.

Error occurred in recognition: network 
It seems like the cause of the problem has been identified as the network.

**Comment by Judiks** [comment]
@chilianer not sure that i able to fix API or Network issue in this case.
