### ISSUE TITLE
Voice Recognition doesn't transcribe correctly in other languages

### ISSUE THREAD

**Issue by NilaierMusic** [Judiks/VoiceShipControl#3]
So, the thing is, i've set language to Russian, Belarussian and Ukranian, but recognized text still outputs it as English, so it tries to interpret Slavic languages as English (not translate them to English). If i speak in English, the text is perfectly captured, even though i've set the language to these three.

Also, typo for "Spoken" in the console logs:
![43_20240207213208](https://github.com/Judiks/VoiceShipControl/assets/86863646/ce13f991-a877-4642-a336-2242415cf777)
Just to clarify, i did completely restart the game every time i've changed the language.

**Comment by NilaierMusic** [comment]
Damn, i made a typo myself in this issue's title 😳

**Comment by NilaierMusic** [comment]
Might not actually work in any other language besides English. I've tried Uzbek, Japanese, Polish and Bulgarian and none of them yield correct transcription in their respective language.

**Comment by Judiks** [comment]
@NilaierMusic Странно проверял на Русском было всё в порядке. Мне уже писали про проблемы с локализацией видимо в коде проблемы перепроверю.
Strangely, I checked in Russian and everything was fine. People have already written to me about problems with localization, apparently I’m double-checking the problems in the code.

Спасибо за реквест

**Comment by Judiks** [comment]
@NilaierMusic fixed you can check with zip folder what connected on github. On thunderstorm it's not available for now because under moderation review.

**Comment by Judiks** [comment]
@NilaierMusic inform me if some of you requests is fixed or if something not clear TY

**Comment by NilaierMusic** [comment]
I think this issue is resolved. Closing it!
